version: '3'
services:
  cf-ddns:
    image: kenfdev/cf-ddns:0.1
    ports:
    - 9080:8080
    environment:
      write_debug: 'true'
      API_KEY: "${API_KEY}"
      EMAIL: 'kenfdev@gmail.com'
      read_timeout: 10
      write_timeout: 10
      exec_timeout: 10
