provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  cf-ddns:
    lang: golang-http
    handler: ./cf-ddns
    image: kenfdev/cf-ddns:0.1
    environment:
      write_debug: 'true'
      read_timeout: 10
      write_timeout: 10
      exec_timeout: 10
      API_KEY: ""
      EMAIL: 'kenfdev@gmail.com'
