// Code generated by mockery v1.0.0
package function

import mock "github.com/stretchr/testify/mock"

// MockDNSService is an autogenerated mock type for the DNSService type
type MockDNSService struct {
	mock.Mock
}

// FetchDNSRecordFor provides a mock function with given fields: zoneName, domainName
func (_m *MockDNSService) FetchDNSRecordFor(zoneName string, domainName string) (*DNSRecord, error) {
	ret := _m.Called(zoneName, domainName)

	var r0 *DNSRecord
	if rf, ok := ret.Get(0).(func(string, string) *DNSRecord); ok {
		r0 = rf(zoneName, domainName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*DNSRecord)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(zoneName, domainName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateDNSRecordIPFor provides a mock function with given fields: zoneID, domains, ip
func (_m *MockDNSService) UpdateDNSRecordIPFor(zoneID string, domains []string, ip string) error {
	ret := _m.Called(zoneID, domains, ip)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []string, string) error); ok {
		r0 = rf(zoneID, domains, ip)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
